### ISSUE TITLE
[클럽생성] 사용자가 저장한 태그를 문자열 형태로 반환 필요

### ISSUE THREAD

**Issue by HaeJinS2** [H99-FinalProj-Moyiza/Moyiza_BE#131]
현재 클럽 생성 시 사용자가 임시로 저장한 태그에 대한 응답이 "0000001110000.." 등의 형식으로 제공되고 있습니다. 
따라서 사용자가 실제로 어떤 값을 저장하고 있는지 파악할 수 없습니다.

임시 저장된 태그 목록을 사용자가 실제로 저장한 문자열(String) 형태로 반환하도록 수정이 필요합니다.

**Comment by mottoslo** [comment]
반영하였습니다
